# Generated by Django 2.1.1 on 2018-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='id_for_api',
            field=models.CharField(default=0, max_length=16, verbose_name='API용 ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catimage',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
