# Generated by Django 2.1.1 on 2018-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20180901_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='id_for_api',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='API용 ID'),
        ),
    ]
